"""MCP prompts for Ameba dev workflow.

Prompts are deliberately terse — they only encode multi-step procedures
the agent would otherwise have to derive on its own. Detailed schemas
and error codes still live in tool docstrings.
"""

from mcp.server.fastmcp import FastMCP


def register_prompts(mcp: FastMCP) -> None:
    @mcp.prompt(
        name="ameba-video-example",
        description="Interactively select a video example, build and flash it.",
    )
    def ameba_video_example() -> str:
        return (
            "Guide the user through selecting, building, and flashing a Pro2 video example.\n"
            "\n"
            "Step 1 — Show the example menu:\n"
            "  Call list_video_examples_tool() to get the full catalog.\n"
            "  Present a grouped list to the user (group by category).\n"
            "  For each entry show: id, name, description, nn_models (or 'no NN').\n"
            "  Mark the currently active example with ★.\n"
            "  Ask (one AskUserQuestion, single-select) which example_id they want.\n"
            "\n"
            "Step 2 — Apply the selection:\n"
            "  Call set_video_example_tool(example_id=<chosen_id>).\n"
            "  Report to the user: name, nn flag, nn_models changed (before → after).\n"
            "\n"
            "Step 3 — Ask which board to flash:\n"
            "  The user may have multiple boards in board_info.json5.\n"
            "  Ask (AskUserQuestion) which board alias to build+flash.\n"
            "\n"
            "Step 4 — Decide pristine:\n"
            "  pristine=True is required when:\n"
            "    • No CMakeCache.txt in the build directory yet (first build).\n"
            "    • Previous build used a non-video example (-DEXAMPLE=xxx).\n"
            "  pristine=True is NOT required when:\n"
            "    • Switching between video examples (source change only).\n"
            "    • Toggling nn=True/False (both use -DVIDEO_EXAMPLE=ON).\n"
            "  Check build_dir/CMakeCache.txt existence to decide; if the user\n"
            "  switched from a non-video build, ask once to confirm.\n"
            "\n"
            "Step 5 — Build:\n"
            "  Call build_firmware(\n"
            "      alias=<board_alias>,\n"
            "      video_example=True,\n"
            "      nn=<result.nn from step 2>,\n"
            "      pristine=<decided in step 4>,\n"
            "  )\n"
            "  Report success/failure; on failure show the relevant log lines.\n"
            "\n"
            "Step 6 — Flash:\n"
            "  Ask the user to put the board into download mode, then call\n"
            "  flash_firmware_tool(alias=<board_alias>).\n"
            "  After flash, remind the user to reset the board.\n"
            "\n"
            "Step 7 — Optional serial monitor:\n"
            "  Ask if the user wants to open the serial monitor.\n"
            "  If yes, call serial_connect_tool(alias=<board_alias>, reset=False)\n"
            "  then serial_read_tool to show initial boot log.\n"
        )

    @mcp.prompt(
        name="ameba-setup-boards",
        description="Bootstrap board_info.json5 in one round-trip.",
    )
    def ameba_setup() -> str:
        return (
            "Bootstrap an AmebaPro2 test bench (local USB only). Drive the\n"
            "conversation so the user is not asked unnecessary questions:\n"
            "\n"
            "Step 1 (FIRST AskUserQuestion — required for everyone):\n"
            "First, check if board_info.json5 already exists in the project root\n"
            "(the directory where ameba.py is run for this project — this is the\n"
            "SDK root for in-SDK development, or the out-of-tree project root when\n"
            "the server was started with --project-root). env_pre_check_tool and\n"
            "apply_board_config_tool report the exact path; trust that over any\n"
            "assumption. Then determine whether it was added or modified.\n"
            "  Gather in one call:\n"
            "    - board_count (int >= 1)\n"
            "  Pro2 always uses local USB — do NOT ask about transport.\n"
            "\n"
            "Step 2 (FREE TEXT, plain question — NOT AskUserQuestion):\n"
            "  Ask the user for their SoCs list (one per board, matching\n"
            "  the board_count from step 1). Show a few examples (e.g.\n"
            "  RTL8735B for Pro2) and make clear any SoC name supported by\n"
            "  this SDK is fine. The SoCs catalog is open-ended.\n"
            "\n"
            "Step 3 (REQUIRED: pair every SoC with its serial port):\n"
            "  apply_board_config_tool needs both `soc` AND `port` for every\n"
            "  board. board_count >= 2 means the agent MUST explicitly ask\n"
            "  the user which port corresponds to which SoC — never assume\n"
            "  the order in step 2 matches the physical order.\n"
            "\n"
            "  Port discovery options:\n"
            "    a) The user already knows the port names (e.g. 'RTL8735B is\n"
            "       on COM3, on ttyUSB0'). Use those directly.\n"
            "    b) The user is unsure of the port names. Then:\n"
            "       call list_serial_ports_tool() to discover local ports.\n"
            "       Show the discovered ports back to the user and ask them\n"
            "       to map each port to a SoC from step 2 (a single round of\n"
            "       AskUserQuestion is fine; for board_count >= 4 a free-text\n"
            "       'list one mapping per line' is also acceptable).\n"
            "\n"
            "  Goal: produce a complete `boards` array shaped like\n"
            "    [ {soc: 'RTL8735B', port: 'COM3'}, ... ]\n"
            "  with one entry per board, ready to hand to apply_board_config_tool.\n"
            "\n"
            "Step 5 (Persist):\n"
            "  Write all entries with apply_board_config_tool, then run\n"
            "  env_pre_check_tool to verify. After success, relay\n"
            "  apply_board_config_tool's `remind_user` text to the user.\n"
            "\n"
            "Step 6 (Offer serial-log auto-recording — ALWAYS ask):\n"
            "  After the bench is saved, ask the user (one AskUserQuestion,\n"
            "  multiSelect over the configured aliases plus a 'None' choice)\n"
            "  whether to turn on automatic serial-log recording for any\n"
            "  board. Explain it in one line: when enabled, every serial\n"
            "  session opened via MCP is captured to a timestamped, AAG\n"
            "  de-interleaved .log file under PROJECT_ROOT/mcp_serial_log/\n"
            "  (one file per day; closing the port stops recording). It is\n"
            "  OPT-IN and OFF by default.\n"
            "  To enable it, apply_board_config_tool does NOT carry this\n"
            "  field — edit board_info.json5 directly and add to the chosen\n"
            "  board entry:\n"
            "        \"serial_log_record\": { \"enable\": true }\n"
            "  Optional keys: \"log_dir\" (default PROJECT_ROOT/mcp_serial_log,\n"
            "  relative paths resolve under PROJECT_ROOT) and \"file_name\"\n"
            "  (default <alias>_<YYYYMMDD>_<HHMMSS>.log, auto-managed; a\n"
            "  custom name is used verbatim and never rotated). If the user\n"
            "  declines, leave it out entirely — do not write enable:false."
        )
